### ISSUE TITLE
Change the ownership of files in directory mode

### ISSUE THREAD

**Issue by palmtop** [m6h/front-dl#2]
Can you implement a way to change the owner from root:root to something else in media mode after download?

E.g. with environment variables PID and GID.

I would like to share the media files via Samba, but if they are all owned by root, external clients can not delete them (or only by a not very secure config).

It is even better if I could also specify the permission mask e.g. 0774 or something similar.

**Comment by m6h** [comment]
Sure thing, i'll work on that

**Comment by m6h** [comment]
Implemented in 186fa1a and 4c83e54, available in build `m60h/front-dl:f902c6e1` or latest.

Can be configured via environment variables (see readme) or the Settings tab:
![image](https://user-images.githubusercontent.com/18387899/84223849-fc291580-aaa8-11ea-9ca9-66febfe0bf51.png)

**Comment by palmtop** [comment]
Thank you, I have just tested, and it has the functionality what I need :-)

In one of the cases it did not change neither the ownership nor the permissions:

https://www.youtube.com/watch?v=Hkvopu9hVd8

On the log I see this messages:

Hkvopu9hVd8: Writing thumbnail to: /media/Alan Walker, Sabrina Carpenter, Farruko - On My Way.jpg
/media/Alan Walker, Sabrina Carpenter, Farruko - On My Way.m4a has already been downloaded [download] 100% of 3.14MiB
Correcting container in "/media/Alan Walker, Sabrina Carpenter, Farruko - On My Way.m4a"
Adding thumbnail to "/media/Alan Walker, Sabrina Carpenter, Farruko - On My Way.m4a"
Download complete

**Comment by m6h** [comment]
I also noticed that while testing. Audio files can have different extensions (`.m4a`, `.mp3`, etc...) so in order to know which extension youtube-dl chose, i parse its log output for a line containing the word "Destination", e.g. `Destination: /media/foo.m4a`. That log output doesn't appear if the file has already been downloaded. Instead you get the line `/media/foo.m4a has already been downloaded`, as you can see in your logs, which causes issues. I might find a better method of getting the correct audio file extension in the future which doesn't rely on that line.

It should work as expected if an audio file with the same name doesn't already exist (i.e. all new downloads). In your case, you could delete that file, redownload it, and the metadata and permissions should get applied.

**Comment by palmtop** [comment]
So I have downloaded it twice. This should not occur often.
Just one idea come to my mind, if you would add a button to apply ownership to all files now, that could be used as an emergency fix for all this kind of problems.

**Comment by m6h** [comment]
Ya i might add a button to do that if it continues to occasionally miss setting permissions in certain cases. I ended up changing the method for finding the file extensions of downloads so it should behave better.
